# Generated by Django 5.0.14 on 2026-07-16 15:38

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_classifications(apps, schema_editor):
    FeedbackRecord = apps.get_model('pipeline', 'FeedbackRecord')
    FeedbackTarget = apps.get_model('pipeline', 'FeedbackTarget')
    FeedbackConsequence = apps.get_model('pipeline', 'FeedbackConsequence')
    for record in FeedbackRecord.objects.iterator():
        if record.inferred_target:
            value = record.inferred_target.strip()
            target_type, _, target_name = value.replace('.', '_').partition('_')
            FeedbackTarget.objects.get_or_create(
                feedback_id=record.id,
                target_type=target_type or 'Feature',
                target_name=target_name or value,
                defaults={'matched_expression': value, 'source': 'legacy', 'is_primary': True},
            )
        if record.consequence:
            FeedbackConsequence.objects.get_or_create(
                feedback_id=record.id,
                consequence_type=record.consequence.strip(),
                defaults={'derivation_rule': 'legacy', 'is_primary': True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_processingjob_domainlexicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrecord',
            name='elicitation_technique',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='DomainLexiconTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=220)),
                ('normalized_expression', models.CharField(max_length=220)),
                ('canonical_name', models.CharField(max_length=220)),
                ('target_type', models.CharField(max_length=80)),
                ('language', models.CharField(default='pt-BR', max_length=20)),
                ('source', models.CharField(default='domain_lexicon', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lexicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='pipeline.domainlexicon')),
            ],
            options={
                'ordering': ['-active', '-normalized_expression'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=120)),
                ('source_hash', models.CharField(max_length=128)),
                ('role_type', models.CharField(blank=True, max_length=80)),
                ('role_source', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='pipeline.processingjob')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackrecord',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='pipeline.feedbackagent'),
        ),
        migrations.CreateModel(
            name='FeedbackConsequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequence_type', models.CharField(max_length=80)),
                ('derivation_rule', models.CharField(blank=True, max_length=160)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequences', to='pipeline.feedbackrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=120)),
                ('browser', models.CharField(blank=True, max_length=120)),
                ('operating_system', models.CharField(blank=True, max_length=120)),
                ('screen', models.CharField(blank=True, max_length=160)),
                ('module', models.CharField(blank=True, max_length=160)),
                ('environment', models.CharField(blank=True, max_length=80)),
                ('source_channel', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='pipeline.feedbackrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=80)),
                ('target_name', models.CharField(max_length=220)),
                ('matched_expression', models.CharField(blank=True, max_length=220)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='pipeline.feedbackrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='domainlexiconterm',
            constraint=models.UniqueConstraint(fields=('lexicon', 'normalized_expression', 'target_type'), name='pipeline_unique_lexicon_term'),
        ),
        migrations.AddConstraint(
            model_name='feedbackagent',
            constraint=models.UniqueConstraint(fields=('job', 'source_hash'), name='pipeline_unique_job_agent'),
        ),
        migrations.AddConstraint(
            model_name='feedbackconsequence',
            constraint=models.UniqueConstraint(fields=('feedback', 'consequence_type'), name='pipeline_unique_feedback_consequence'),
        ),
        migrations.AddConstraint(
            model_name='feedbackconsequence',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('feedback',), name='pipeline_one_primary_consequence'),
        ),
        migrations.AddConstraint(
            model_name='feedbacktarget',
            constraint=models.UniqueConstraint(fields=('feedback', 'target_type', 'target_name'), name='pipeline_unique_feedback_target'),
        ),
        migrations.AddConstraint(
            model_name='feedbacktarget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('feedback',), name='pipeline_one_primary_target'),
        ),
        migrations.RunPython(migrate_legacy_classifications, migrations.RunPython.noop),
    ]
